dist: trusty
language: python
python:
  - "3.6"

sudo: required


addons:
  apt:
    packages:
     - wget
     - unzip
     - build-essential
     - python3
     - automake
     - libgmp-dev
     - curl
     - nano
     - python3-dev
     - libboost-dev
     - default-jdk
     - libclang-dev
     - llvm
     - llvm-dev
     - lbzip2
     - libncurses5-dev
     - python3-nose

install:
  -  bash travis_install.sh

env:
 - PYTHONPATH="/home/travis/.smt_solvers/python-bindings-3.6:${PYTHONPATH}" LD_LIBRARY_PATH="/home/travis/.smt_solvers/python-bindings-3.6:${LD_LIBRARY_PATH}"


script: nosetests3 tests -v