dist: xenial
language: python
python:
  - "3.6"
  - "3.5"
  - "3.4"

sudo: required

cache:
  directories:
  - ${TRAVIS_BUILD_DIR}/pycoreir
  - ${TRAVIS_BUILD_DIR}/pysmt
  - ${TRAVIS_BUILD_DIR}/coreir
  - /home/travis/.smt_solvers/python-bindings-3.6

addons:
  apt:
    update: true
    sources:
    - ubuntu-toolchain-r-test
    packages:
     - g++-4.9
     - clang
     - wget
     - unzip
     - build-essential
     - python3
     - automake
     - libgmp-dev
     - curl
     - nano
     - python3-dev
     - libboost-dev
     - default-jdk
     - libclang-dev
     - llvm
     - llvm-dev
     - lbzip2
     - libncurses5-dev
     - python3-nose
     - iverilog
     - libreadline-dev
     - libmpfr-dev
     - libmpc-dev

install:
  - pip install -e .
  - bash ./scripts/travis_install.sh
  - chmod +x ./yosys

env:
 - PATH="$PATH:." PYTHONPATH="${TRAVIS_BUILD_DIR}/pycoreir":"${TRAVIS_BUILD_DIR}/pysmt":"${TRAVIS_BUILD_DIR}/pysmt/bindings:${PYTHONPATH}" LD_LIBRARY_PATH="${TRAVIS_BUILD_DIR}/coreir/lib":"${TRAVIS_BUILD_DIR}/pysmt/bindings:${LD_LIBRARY_PATH}" COREIRCONFIG=clang++ CC=clang CXX=clang++

script: nosetests tests -vv
